### ISSUE TITLE
The Addition of Dr. Reflex

### ISSUE THREAD

**Issue by Omaruu-Dev** [Fasguy/BaldisBasicsModMenu-archive#114] opened 2024-03-26 23:17 UTC
**Why do you need this feature?**
Not really a need per se but id like to add Dr.Reflex into BBCR

It'd be fun to challenge myself with all characters enabled

**Describe the feature**
A clear and concise description of what the feature is

Adding Dr. Reflex's Character into Baldi's Basics Classic Remastered you dont even need to add his room

he ability to spawn the Null/Glitch Style Throwable desks to activate the boss fight in any style

If youre able to add these in an update that would be appreciated ^^

**Comment by Fasguy** [comment] 2024-03-27 02:11
Duplicate of #103

**Closed as not planned by Fasguy** 2024-03-27 02:11 UTC
