### ISSUE TITLE
baldis basics + mod menu pls add this to the archive

### ISSUE THREAD

**Issue by baldiandbonzifan** [Fasguy/BaldisBasicsModMenu-archive#136] opened 2024-10-13 00:54 UTC
**Why do you need this feature?**
i love ur md menu but since i got baldis basics Plus the modmenu by oldsport SUCKS so thats why

**Describe the feature**
its just like the one on bbcr but  no null and this is the new characters there
dr reflex
the test 
and more
it still has events
so pls i want it
i dont like olsport

**Comment by Fasguy** [comment] 2024-10-13 05:23
Effective duplicate of #16

**Closed as not planned by Fasguy** 2024-10-13 05:23 UTC
Labels: duplicate, invalid, Plus
