### ISSUE TITLE
Vending machine feature

### ISSUE THREAD

**Issue by floridatanft** [Fasguy/BaldisBasicsModMenu-archive#135] opened 2024-09-19 20:52 UTC
**Why do you need this feature?**
I think it would be useful for many players.

**Describe the feature**
A toggle switch under gameplay modifiers that allows you to define whether you can use a vending machine infinitely rather than once (off by default)

Classic Remastered

**Comment by Fasguy** [comment] 2024-12-07 11:35
Duplicate of #86

**Closed as not planned by Fasguy** 2024-12-07 11:35 UTC
Labels: duplicate
