### ISSUE TITLE
Health modifier for NULL

### ISSUE THREAD

**Issue by FILENAME099** [Fasguy/BaldisBasicsModMenu-archive#116] opened 2024-03-30 17:36 UTC
**Why do you need this feature?**
Describe why you're suggesting this feature
Makes the bossfight better for NULL

**Describe the feature**
A clear and concise description of what the feature is.
Modifies how many hits NULL can take before getting sent to the developer's office.

**Comment by Fasguy** [comment] 2024-03-30 17:38
Duplicate of #27

**Closed as not planned by Fasguy** 2024-03-30 17:38 UTC
